### ISSUE TITLE
why do you use Redis Pubsub

### ISSUE THREAD

**Issue by MaryLilian** [Lack-Zillions-Over/zensky#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me  it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by GuilhermeSantos001** [comment]
## DISCLAIMER

> If you need a robust messaging system with fault prediction, support for large message loads, queueing, complex message distribution, and other key features, you should not use Redis!

Try [RabbitMQ](https://www.rabbitmq.com/) or [Apache Kafka](https://kafka.apache.org/), both need the correct settings to have 100% of the expected performance, it is not enough to just install and add the driver to the project.


### Actually there is the [sapphire](https://github.com/Lack-Zillions-Over/sapphire) project that uses RabbitMQ.

I intend to have three projects with Pub/Sub support for different technologies, Redis, RabbitMQ and Apache Kafka.

About advantage or disadvantage of using Redis, compared to RabbitMQ or Kafka, Redis is a key-value database, i.e. it is not meant to manage, scale, secure, provision or anything else related to messaging. It simply stores data in memory and because of this, Pub/Sub support was created.
